[package]
name = "substrate-state-machine"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate State Machine"

[dependencies]
byteorder = "1.1"
hex-literal = "0.1.0"
log = "0.3"
parking_lot = "0.4"
heapsize = "0.4"

substrate-primitives = { path = "../primitives", version = "0.1.0" }

hashdb = { git = "https://github.com/paritytech/parity-common", branch = "temp/combined-hashdb-plain_hasher-changes" }
memorydb = { git = "https://github.com/paritytech/parity-common", branch = "temp/combined-hashdb-plain_hasher-changes" }
patricia-trie = { git = "https://github.com/paritytech/parity-common", branch = "temp/combined-hashdb-plain_hasher-changes" }
triehash = { git = "https://github.com/paritytech/parity-common", branch = "temp/combined-hashdb-plain_hasher-changes" }
rlp = { git = "https://github.com/paritytech/parity-common", branch = "temp/combined-hashdb-plain_hasher-changes" }
